# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88a324913e766642d29cf46250f86ee276140e9908eb36eedfbc7c79dc0489536957b536fe42848fc78a6a9bbe965773330ac28f430b43d550545ccf6a7a0d59

test:
  secret_key_base: 91050b963a8aa9466937eeccf0d3ab40a944e9cd99d2ac14b1ca3521416d6c6a2bdc3f625ec571b1558e518de65430aec573c8d2da226e62b617a6b659b1c02d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
